name: Build and Deploy Book to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build file list
        id: file_list
        run: |
          mkdir docs
          echo "files=$(printf '"%s" ' *.md)" > $GITHUB_OUTPUT

      - name: Set up pandoc
        uses: docker://pandoc/core:3.5
        with:
          args: >-
            --number-sections 
            --toc=true --toc-depth=1 
            -s -c style.css 
            -t chunkedhtml 
            --data-dir=pandoc/ 
            ${{ steps.file_list.outputs.files }}
            -o docs/book.zip

      - name: unpack book, add css
        run: |
          unzip -q -d docs docs/book.zip
          cp style.css docs

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
